// ==UserScript==
// @name         Data Collector for Google Sheets
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  Collects data from URLs and saves to Google Sheets
// @match        *://*/*
// @grant        GM_xmlhttpRequest
// @grant        GM_addStyle
// ==/UserScript==

(function() {
    'use strict';
    const urls = [
        "https://edu.21-school.ru/profile/harveyfa",
        "https://edu.21-school.ru/profile/addisoja",
        "https://edu.21-school.ru/profile/adelleyo",
        "https://edu.21-school.ru/profile/agneslef",
        "https://edu.21-school.ru/profile/agustinp",
        "https://edu.21-school.ru/profile/aionstre",
        "https://edu.21-school.ru/profile/alcairma",
        "https://edu.21-school.ru/profile/alethasa",
        "https://edu.21-school.ru/profile/alivelaz",
        "https://edu.21-school.ru/profile/amchurke",
        "https://edu.21-school.ru/profile/anakinlo",
        "https://edu.21-school.ru/profile/andimeku",
        "https://edu.21-school.ru/profile/angelyou",
        "https://edu.21-school.ru/profile/aniseeda",
        "https://edu.21-school.ru/profile/anisemot",
        "https://edu.21-school.ru/profile/annetter",
        "https://edu.21-school.ru/profile/antionek",
        "https://edu.21-school.ru/profile/antoninp",
        "https://edu.21-school.ru/profile/apollope",
        "https://edu.21-school.ru/profile/ashfordp",
        "https://edu.21-school.ru/profile/ashtonmi",
        "https://edu.21-school.ru/profile/athenado",
        "https://edu.21-school.ru/profile/athenasa",
        "https://edu.21-school.ru/profile/aurielda",
        "https://edu.21-school.ru/profile/babblian",
        "https://edu.21-school.ru/profile/bagshota",
        "https://edu.21-school.ru/profile/bandypic",
        "https://edu.21-school.ru/profile/barneyri",
        "https://edu.21-school.ru/profile/bartemit",
        "https://edu.21-school.ru/profile/bathsheo",
        "https://edu.21-school.ru/profile/bernarbo",
        "https://edu.21-school.ru/profile/bernettr",
        "https://edu.21-school.ru/profile/bicyclei",
        "https://edu.21-school.ru/profile/boardald",
        "https://edu.21-school.ru/profile/bobaobar",
        "https://edu.21-school.ru/profile/bonitaje",
        "https://edu.21-school.ru/profile/boobareb",
        "https://edu.21-school.ru/profile/bouvierk",
        "https://edu.21-school.ru/profile/bretteli",
        "https://edu.21-school.ru/profile/brigetli",
        "https://edu.21-school.ru/profile/bruscobe",
        "https://edu.21-school.ru/profile/bunnyfra",
        "https://edu.21-school.ru/profile/carleedo",
        "https://edu.21-school.ru/profile/cassicha",
        "https://edu.21-school.ru/profile/catwomaw",
        "https://edu.21-school.ru/profile/chalmera",
        "https://edu.21-school.ru/profile/charlinf",
        "https://edu.21-school.ru/profile/charmaia",
        "https://edu.21-school.ru/profile/cheetahd",
        "https://edu.21-school.ru/profile/chelseym",
        "https://edu.21-school.ru/profile/cinthimo",
        "https://edu.21-school.ru/profile/coarsewa",
        "https://edu.21-school.ru/profile/coletthi",
        "https://edu.21-school.ru/profile/cometfor",
        "https://edu.21-school.ru/profile/congerba",
        "https://edu.21-school.ru/profile/conningi",
        "https://edu.21-school.ru/profile/corazowa",
        "https://edu.21-school.ru/profile/criusela",
        "https://edu.21-school.ru/profile/custardj",
        "https://edu.21-school.ru/profile/danellma",
        "https://edu.21-school.ru/profile/dathomie",
        "https://edu.21-school.ru/profile/debbican",
        "https://edu.21-school.ru/profile/debicirc",
        "https://edu.21-school.ru/profile/denvecra",
        "https://edu.21-school.ru/profile/denyoani",
        "https://edu.21-school.ru/profile/desiraca",
        "https://edu.21-school.ru/profile/despersi",
        "https://edu.21-school.ru/profile/digletta",
        "https://edu.21-school.ru/profile/dirkwend",
        "https://edu.21-school.ru/profile/dixiemea",
        "https://edu.21-school.ru/profile/donettaj",
        "https://edu.21-school.ru/profile/dorethas",
        "https://edu.21-school.ru/profile/dovieden",
        "https://edu.21-school.ru/profile/dronmare",
        "https://edu.21-school.ru/profile/drusilgr",
        "https://edu.21-school.ru/profile/drusilsa",
        "https://edu.21-school.ru/profile/dwanagla",
        "https://edu.21-school.ru/profile/echobart",
        "https://edu.21-school.ru/profile/eleneked",
        "https://edu.21-school.ru/profile/elliegre",
        "https://edu.21-school.ru/profile/emiledel",
        "https://edu.21-school.ru/profile/emilialu",
        "https://edu.21-school.ru/profile/ermarebb",
        "https://edu.21-school.ru/profile/ermelinc",
        "https://edu.21-school.ru/profile/eulafang",
        "https://edu.21-school.ru/profile/evelinel",
        "https://edu.21-school.ru/profile/felishae",
        "https://edu.21-school.ru/profile/flammeje",
        "https://edu.21-school.ru/profile/fletchel",
        "https://edu.21-school.ru/profile/foragejo",
        "https://edu.21-school.ru/profile/francoib",
        "https://edu.21-school.ru/profile/galinago",
        "https://edu.21-school.ru/profile/garensar",
        "https://edu.21-school.ru/profile/gooseren",
        "https://edu.21-school.ru/profile/grahareb",
        "https://edu.21-school.ru/profile/grandros",
        "https://edu.21-school.ru/profile/grazynro",
        "https://edu.21-school.ru/profile/halfhanb",
        "https://edu.21-school.ru/profile/halleygl",
        "https://edu.21-school.ru/profile/hamishsu",
        "https://edu.21-school.ru/profile/hawickma",
        "https://edu.21-school.ru/profile/hawkmanb",
        "https://edu.21-school.ru/profile/hisakoer",
        "https://edu.21-school.ru/profile/hopebill",
        "https://edu.21-school.ru/profile/horsetra",
        "https://edu.21-school.ru/profile/hosniasw",
        "https://edu.21-school.ru/profile/houndwom",
        "https://edu.21-school.ru/profile/hungariw",
        "https://edu.21-school.ru/profile/illaoido",
        "https://edu.21-school.ru/profile/illustrd",
        "https://edu.21-school.ru/profile/iolaglor",
        "https://edu.21-school.ru/profile/irinaidd",
        "https://edu.21-school.ru/profile/ironsare",
        "https://edu.21-school.ru/profile/jacktory",
        "https://edu.21-school.ru/profile/jamasari",
        "https://edu.21-school.ru/profile/jasonarc",
        "https://edu.21-school.ru/profile/jaycelem",
        "https://edu.21-school.ru/profile/jennadar",
        "https://edu.21-school.ru/profile/jeramylu",
        "https://edu.21-school.ru/profile/jerebudd",
        "https://edu.21-school.ru/profile/joeykris",
        "https://edu.21-school.ru/profile/joffreyk",
        "https://edu.21-school.ru/profile/jonnieba",
        "https://edu.21-school.ru/profile/josiahdw",
        "https://edu.21-school.ru/profile/junkrase",
        "https://edu.21-school.ru/profile/justiclo",
        "https://edu.21-school.ru/profile/katheimw",
        "https://edu.21-school.ru/profile/katheran",
        "https://edu.21-school.ru/profile/keelyhel",
        "https://edu.21-school.ru/profile/kendalcr",
        "https://edu.21-school.ru/profile/kenyettk",
        "https://edu.21-school.ru/profile/kerriedd",
        "https://edu.21-school.ru/profile/kierstep",
        "https://edu.21-school.ru/profile/kleinesh",
        "https://edu.21-school.ru/profile/ladonnak",
        "https://edu.21-school.ru/profile/lakenyas",
        "https://edu.21-school.ru/profile/lalatequ",
        "https://edu.21-school.ru/profile/laquandc",
        "https://edu.21-school.ru/profile/laruegue",
        "https://edu.21-school.ru/profile/lashundh",
        "https://edu.21-school.ru/profile/latinaka",
        "https://edu.21-school.ru/profile/launasha",
        "https://edu.21-school.ru/profile/lavernpe",
        "https://edu.21-school.ru/profile/lawanasa",
        "https://edu.21-school.ru/profile/leekbinn",
        "https://edu.21-school.ru/profile/levantra",
        "https://edu.21-school.ru/profile/linclerp",
        "https://edu.21-school.ru/profile/linseyvo",
        "https://edu.21-school.ru/profile/longwatm",
        "https://edu.21-school.ru/profile/louisapa",
        "https://edu.21-school.ru/profile/lucanval",
        "https://edu.21-school.ru/profile/luciebri",
        "https://edu.21-school.ru/profile/luluspee",
        "https://edu.21-school.ru/profile/lynderlg",
        "https://edu.21-school.ru/profile/lytlebus",
        "https://edu.21-school.ru/profile/macnaito",
        "https://edu.21-school.ru/profile/magdalah",
        "https://edu.21-school.ru/profile/mallorka",
        "https://edu.21-school.ru/profile/mannlidi",
        "https://edu.21-school.ru/profile/margareh",
        "https://edu.21-school.ru/profile/martaial",
        "https://edu.21-school.ru/profile/marvolos",
        "https://edu.21-school.ru/profile/marylins",
        "https://edu.21-school.ru/profile/mattharf",
        "https://edu.21-school.ru/profile/maxonvul",
        "https://edu.21-school.ru/profile/mayamugg",
        "https://edu.21-school.ru/profile/mellatho",
        "https://edu.21-school.ru/profile/merianns",
        "https://edu.21-school.ru/profile/meridits",
        "https://edu.21-school.ru/profile/mjollfis",
        "https://edu.21-school.ru/profile/moonstom",
        "https://edu.21-school.ru/profile/morfinap",
        "https://edu.21-school.ru/profile/needfuls",
        "https://edu.21-school.ru/profile/nellydar",
        "https://edu.21-school.ru/profile/nicholsk",
        "https://edu.21-school.ru/profile/nightemm",
        "https://edu.21-school.ru/profile/norikoda",
        "https://edu.21-school.ru/profile/ophionmo",
        "https://edu.21-school.ru/profile/overdewk",
        "https://edu.21-school.ru/profile/paleorei",
        "https://edu.21-school.ru/profile/parrotfc",
        "https://edu.21-school.ru/profile/patillur",
        "https://edu.21-school.ru/profile/patrinas",
        "https://edu.21-school.ru/profile/pecancur",
        "https://edu.21-school.ru/profile/phanesbo",
        "https://edu.21-school.ru/profile/phinease",
        "https://edu.21-school.ru/profile/pickleju",
        "https://edu.21-school.ru/profile/pizzafra",
        "https://edu.21-school.ru/profile/plutarca",
        "https://edu.21-school.ru/profile/primeelv",
        "https://edu.21-school.ru/profile/profitor",
        "https://edu.21-school.ru/profile/qothjane",
        "https://edu.21-school.ru/profile/racheley",
        "https://edu.21-school.ru/profile/randaswo",
        "https://edu.21-school.ru/profile/reenaala",
        "https://edu.21-school.ru/profile/rigelsty",
        "https://edu.21-school.ru/profile/ronagwyn",
        "https://edu.21-school.ru/profile/rosalinc",
        "https://edu.21-school.ru/profile/roslycel",
        "https://edu.21-school.ru/profile/roxannet",
        "https://edu.21-school.ru/profile/roxychry",
        "https://edu.21-school.ru/profile/rygerend",
        "https://edu.21-school.ru/profile/saathobr",
        "https://edu.21-school.ru/profile/samirasi",
        "https://edu.21-school.ru/profile/sammieja",
        "https://edu.21-school.ru/profile/sanchezj",
        "https://edu.21-school.ru/profile/santagaa",
        "https://edu.21-school.ru/profile/santodat",
        "https://edu.21-school.ru/profile/scenestv",
        "https://edu.21-school.ru/profile/sealsklo",
        "https://edu.21-school.ru/profile/seitanbe",
        "https://edu.21-school.ru/profile/semberei",
        "https://edu.21-school.ru/profile/seymourm",
        "https://edu.21-school.ru/profile/shandrsh",
        "https://edu.21-school.ru/profile/shanellh",
        "https://edu.21-school.ru/profile/sharenme",
        "https://edu.21-school.ru/profile/sionahar",
        "https://edu.21-school.ru/profile/sirynhob",
        "https://edu.21-school.ru/profile/siskogru",
        "https://edu.21-school.ru/profile/skipjacn",
        "https://edu.21-school.ru/profile/slowpoks",
        "https://edu.21-school.ru/profile/slytherm",
        "https://edu.21-school.ru/profile/snowbalm",
        "https://edu.21-school.ru/profile/solomonk",
        "https://edu.21-school.ru/profile/stafford",
        "https://edu.21-school.ru/profile/starksle",
        "https://edu.21-school.ru/profile/stephanj",
        "https://edu.21-school.ru/profile/stevered",
        "https://edu.21-school.ru/profile/stewbonz",
        "https://edu.21-school.ru/profile/stonehar",
        "https://edu.21-school.ru/profile/stoneuol",
        "https://edu.21-school.ru/profile/sturgisc",
        "https://edu.21-school.ru/profile/suttonfe",
        "https://edu.21-school.ru/profile/szechush",
        "https://edu.21-school.ru/profile/tanglean",
        "https://edu.21-school.ru/profile/tarbecac",
        "https://edu.21-school.ru/profile/tennilma",
        "https://edu.21-school.ru/profile/tentaclt",
        "https://edu.21-school.ru/profile/theyange",
        "https://edu.21-school.ru/profile/tonksale",
        "https://edu.21-school.ru/profile/torwoldb",
        "https://edu.21-school.ru/profile/trevaded",
        "https://edu.21-school.ru/profile/tumitish",
        "https://edu.21-school.ru/profile/vanishde",
        "https://edu.21-school.ru/profile/vaynewhi",
        "https://edu.21-school.ru/profile/vickijil",
        "https://edu.21-school.ru/profile/violinde",
        "https://edu.21-school.ru/profile/wallacee",
        "https://edu.21-school.ru/profile/warehouf",
        "https://edu.21-school.ru/profile/wartzcar",
        "https://edu.21-school.ru/profile/weepervi",
        "https://edu.21-school.ru/profile/westanni",
        "https://edu.21-school.ru/profile/wigglytc",
        "https://edu.21-school.ru/profile/willeneb",
        "https://edu.21-school.ru/profile/windomde",
        "https://edu.21-school.ru/profile/xanderel",
        "https://edu.21-school.ru/profile/xuanweav",
        "https://edu.21-school.ru/profile/yajaimet",
        "https://edu.21-school.ru/profile/yongbroo",
        "https://edu.21-school.ru/profile/zeddmorp",
        "https://edu.21-school.ru/profile/zienyaty",
        "https://edu.21-school.ru/profile/zubergal",
        "https://edu.21-school.ru/profile/Давид",
        "https://edu.21-school.ru/profile/Женя",
        "https://edu.21-school.ru/profile/Сон",
        "https://edu.21-school.ru/profile/coconuth",
        "https://edu.21-school.ru/profile/pollivma",
        "https://edu.21-school.ru/profile/arlievic",
        "https://edu.21-school.ru/profile/arpsforg",
        "https://edu.21-school.ru/profile/ashleigk",
        "https://edu.21-school.ru/profile/bachmank",
        "https://edu.21-school.ru/profile/baermits",
        "https://edu.21-school.ru/profile/beerusra",
        "https://edu.21-school.ru/profile/bertbran",
        "https://edu.21-school.ru/profile/biffmake",
        "https://edu.21-school.ru/profile/blackier",
        "https://edu.21-school.ru/profile/blobsyla",
        "https://edu.21-school.ru/profile/borosven",
        "https://edu.21-school.ru/profile/braxscyt",
        "https://edu.21-school.ru/profile/charlosh",
        "https://edu.21-school.ru/profile/chatayph",
        "https://edu.21-school.ru/profile/clarinej",
        "https://edu.21-school.ru/profile/clytemco",
        "https://edu.21-school.ru/profile/cornmeab",
        "https://edu.21-school.ru/profile/corriede",
        "https://edu.21-school.ru/profile/crispclo",
        "https://edu.21-school.ru/profile/daariomi",
        "https://edu.21-school.ru/profile/darcymer",
        "https://edu.21-school.ru/profile/deathlow",
        "https://edu.21-school.ru/profile/dedalusj",
        "https://edu.21-school.ru/profile/delorsch",
        "https://edu.21-school.ru/profile/demetrba",
        "https://edu.21-school.ru/profile/edythjes",
        "https://edu.21-school.ru/profile/eleomarg",
        "https://edu.21-school.ru/profile/ellisutt",
        "https://edu.21-school.ru/profile/ezekiear",
        "https://edu.21-school.ru/profile/falenari",
        "https://edu.21-school.ru/profile/fenrirti",
        "https://edu.21-school.ru/profile/floraole",
        "https://edu.21-school.ru/profile/galtryca",
        "https://edu.21-school.ru/profile/gerussem",
        "https://edu.21-school.ru/profile/ghislett",
        "https://edu.21-school.ru/profile/goosehan",
        "https://edu.21-school.ru/profile/grapesno",
        "https://edu.21-school.ru/profile/greychan",
        "https://edu.21-school.ru/profile/grunthoq",
        "https://edu.21-school.ru/profile/gwinprim",
        "https://edu.21-school.ru/profile/harrenma",
        "https://edu.21-school.ru/profile/helyairo",
        "https://edu.21-school.ru/profile/herbesca",
        "https://edu.21-school.ru/profile/herschep",
        "https://edu.21-school.ru/profile/hilarysw",
        "https://edu.21-school.ru/profile/holleyde",
        "https://edu.21-school.ru/profile/hollisdi",
        "https://edu.21-school.ru/profile/jacquere",
        "https://edu.21-school.ru/profile/jashoomo",
        "https://edu.21-school.ru/profile/jennellf",
        "https://edu.21-school.ru/profile/jessipha",
        "https://edu.21-school.ru/profile/jewishas",
        "https://edu.21-school.ru/profile/kabutomi",
        "https://edu.21-school.ru/profile/kathrynr",
        "https://edu.21-school.ru/profile/kavulala",
        "https://edu.21-school.ru/profile/kegsbear",
        "https://edu.21-school.ru/profile/kegsfran",
        "https://edu.21-school.ru/profile/kennedcl",
        "https://edu.21-school.ru/profile/kentdoze",
        "https://edu.21-school.ru/profile/kirkdraq",
        "https://edu.21-school.ru/profile/kirstibo",
        "https://edu.21-school.ru/profile/krabappc",
        "https://edu.21-school.ru/profile/lannistp",
        "https://edu.21-school.ru/profile/leesaame",
        "https://edu.21-school.ru/profile/lillycat",
        "https://edu.21-school.ru/profile/lockesan",
        "https://edu.21-school.ru/profile/loralang",
        "https://edu.21-school.ru/profile/lordsedg",
        "https://edu.21-school.ru/profile/maarheir",
        "https://edu.21-school.ru/profile/magareju",
        "https://edu.21-school.ru/profile/mahasima",
        "https://edu.21-school.ru/profile/marciada",
        "https://edu.21-school.ru/profile/maricpat",
        "https://edu.21-school.ru/profile/meowthar",
        "https://edu.21-school.ru/profile/merilylo",
        "https://edu.21-school.ru/profile/mimiblin",
        "https://edu.21-school.ru/profile/motherhe",
        "https://edu.21-school.ru/profile/muncitek",
        "https://edu.21-school.ru/profile/nashiall",
        "https://edu.21-school.ru/profile/neelylan",
        "https://edu.21-school.ru/profile/newtanax",
        "https://edu.21-school.ru/profile/ninaknap",
        "https://edu.21-school.ru/profile/ocleluco",
        "https://edu.21-school.ru/profile/omniscit",
        "https://edu.21-school.ru/profile/orientat",
        "https://edu.21-school.ru/profile/overdewm",
        "https://edu.21-school.ru/profile/paulettr",
        "https://edu.21-school.ru/profile/persimma",
        "https://edu.21-school.ru/profile/persimmr",
        "https://edu.21-school.ru/profile/pharahal",
        "https://edu.21-school.ru/profile/quayniro",
        "https://edu.21-school.ru/profile/queenray",
        "https://edu.21-school.ru/profile/rebecara",
        "https://edu.21-school.ru/profile/rooseles",
        "https://edu.21-school.ru/profile/roselias",
        "https://edu.21-school.ru/profile/rositabl",
        "https://edu.21-school.ru/profile/rudolfli",
        "https://edu.21-school.ru/profile/selwynka",
        "https://edu.21-school.ru/profile/shadoutr",
        "https://edu.21-school.ru/profile/sharanan",
        "https://edu.21-school.ru/profile/sherillf",
        "https://edu.21-school.ru/profile/starshic",
        "https://edu.21-school.ru/profile/tarbeckh",
        "https://edu.21-school.ru/profile/tarlepev",
        "https://edu.21-school.ru/profile/thorlula",
        "https://edu.21-school.ru/profile/tightlim",
        "https://edu.21-school.ru/profile/toraqcat",
        "https://edu.21-school.ru/profile/trishaca",
        "https://edu.21-school.ru/profile/tyishawo",
        "https://edu.21-school.ru/profile/tyraelbe",
        "https://edu.21-school.ru/profile/uthornor",
        "https://edu.21-school.ru/profile/viviennm",
        "https://edu.21-school.ru/profile/waltshar",
        "https://edu.21-school.ru/profile/warelorn",
        "https://edu.21-school.ru/profile/weetholl",
        "https://edu.21-school.ru/profile/yasminec",
        "https://edu.21-school.ru/profile/yvonemee",
    ];
    const xpath = '//*[@id="root"]/div[2]/div/section/div[1]/div[1]/div/div[7]/div[2]/span';
    const scriptId = 'AKfycbyeZD49vjki0i69XD9JbDvymdnNqjopDP61b3cv0mO5pl2cz1PiTS1ByzadJFeHzZM';

    function createButton() {
        const btn = document.createElement('button');
        btn.textContent = 'Start Collection';
        Object.assign(btn.style, {
            position: 'fixed',
            top: '20px',
            right: '20px',
            zIndex: 9999,
            padding: '10px',
            background: '#4CAF50',
            color: 'white',
            border: 'none',
            borderRadius: '4px',
            cursor: 'pointer'
        });
        btn.addEventListener('click', startProcessing);
        document.body.appendChild(btn);
    }

    async function startProcessing() {
        for (const url of urls) {
            const tab = window.open(url, '_blank');
            await new Promise(resolve => setTimeout(resolve, 10000));

            try {
                const result = tab.document.evaluate(xpath, tab.document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null);
                const text = result.singleNodeValue?.textContent?.trim() || 'Not found';
                updateSheet(url, text);
            } catch (error) {
                console.error('Error processing URL:', url, error);
            }

            tab.close();
            await new Promise(resolve => setTimeout(resolve, 1000));
        }
    }

    function updateSheet(url, text) {
        GM_xmlhttpRequest({
            method: 'POST',
            url: `https://script.google.com/macros/s/${scriptId}/exec`,
            data: JSON.stringify({url, text}),
            headers: {'Content-Type': 'application/json'},
            onload: function(response) {
                console.log('Sheet updated:', response.responseText);
            }
        });
    }

    if (!document.querySelector('button[style*="z-index: 9999"]')) {
        createButton();
    }
})();